// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package interfaces

import (
	"context"
	"ddd-demo-go/application/appservice"
	"ddd-demo-go/application/dto"
	"ddd-demo-go/infrastructure/adapter"
	"ddd-demo-go/infrastructure/common/cache"
	"ddd-demo-go/infrastructure/common/db"
	"ddd-demo-go/infrastructure/common/logit"
	"ddd-demo-go/infrastructure/common/request"
	"ddd-demo-go/infrastructure/common/response"
	"ddd-demo-go/infrastructure/po"
	"ddd-demo-go/infrastructure/repository"
	"ddd-demo-go/interfaces/http"
	"ddd-demo-go/interfaces/http/controller"
)

// Injectors from wire.go:

func NewApp(ctx context.Context) (*app, error) {
	serviceLoggerConf, err := logit.NewServiceLoggerConf()
	if err != nil {
		return nil, err
	}
	loggerInterface, err := logit.NewServiceLogger(serviceLoggerConf)
	if err != nil {
		return nil, err
	}
	appConf, err := loadAppConf()
	if err != nil {
		return nil, err
	}
	bindInterface := request.NewRequest(loggerInterface)
	httpResponseInterface := response.NewHTTPResponseWriter(loggerInterface)
	orderConv := dto.NewOrderConv()
	userAdapter := adapter.NewUserAdapter()
	dbDB, err := db.NewDB()
	if err != nil {
		return nil, err
	}
	orderPOConv := po.NewOrderPOConv()
	orderRepository := repository.NewOrderRepository(dbDB, orderPOConv)
	orderAS := appservice.NewOrderAS(orderConv, userAdapter, orderRepository)
	order := controller.NewOrder(bindInterface, httpResponseInterface, orderAS)
	redis, err := cache.NewRedis()
	if err != nil {
		return nil, err
	}
	health := controller.NewHealth(httpResponseInterface, redis)
	handler := http.NewHTTPHandler(loggerInterface, order, health, httpResponseInterface)
	server, err := newHTTPServer(appConf, handler)
	if err != nil {
		return nil, err
	}
	interfacesApp := &app{
		ctx:        ctx,
		logger:     loggerInterface,
		conf:       appConf,
		httpServer: server,
	}
	return interfacesApp, nil
}
